---
# https://github.com/codecov/example-perl/blob/master/github.yml
name: Code coverage - codecov.io

on:
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: codecov
    container:
      image: perl:stable
    steps:
      - uses: actions/checkout@v4
      - run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          # curl -Os https://cli.codecov.io/latest/linux/codecov
          # chmod +x codecov
          cpanm --quiet --notest --installdeps .
          cpanm --quiet --notest Module::Build Devel::Cover Devel::Cover::Report::Codecov
          perl Makefile.PL
          make
          cover -test -report codecov
          # bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f cover_db/codecov.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
